export const ACTIONS = {
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	SIGNUP: "SIGNUP",
	ADD_TEAM: "ADD_TEAM",
	ADD_RESULTS: "ADD_RESULTS",
	GET_MATCH: "GET_MATCH",
	GET_ALL_MATCHES_BY_CHAMPIONSHIP: "GET_ALL_MATCHES_BY_CHAMPIONSHIP",
	GET_ALL_TEAMS_BY_CHAMPIONSHIP: "GET_ALL_TEAMS_BY_CHAMPIONSHIP",
	EDIT_MATCH: "EDIT_MATCH",
	CONFIRM_CHAMPIONSHIP: "CONFIRM_CHAMPIONSHIP"
};
